name: Bug report
description: Report a problem to help us improve
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Step-by-step reproduction instructions.
      placeholder: 1) Go to..., 2) Click..., 3) See error
  - type: input
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - frontend
        - backend
        - infra/ci
  - type: input
    id: version
    attributes:
      label: Version/commit
  - type: textarea
    id: notes
    attributes:
      label: Additional context


